### ISSUE TITLE
Move away from react-app ESLint config

### ISSUE THREAD

**Issue by vernondegoede** [mollie/eslint-config-mollie#4]
We're currently extending the `react-app` ESLint config, which has `eslint-plugin-flowtype` as a dependency. This does not make sense for React projects that are not flow-typed.

We could move away from that package and include its config in our own `eslint-config-react` package.

Thoughts? @Marinolinderhof @mattijsbliek

**Comment by mattijsbliek** [comment]
I’m assuming the rules only kick in for files that have `// @flow` at the top of them right? So there is no real harm done when the project does not use Flow?

Leveraging existing configs would have my preference, since it makes it easier for us to stay up to date.

**Comment by Marinolinderhof** [comment]
Is there a rule that currently bothering you? If not it doesn't really matter. This is how CRA does it:
https://github.com/facebook/create-react-app/blob/master/packages/eslint-config-react-app/package.json

https://github.com/facebook/create-react-app/blob/67e8e2cba61fee0e16c026b0ea064b5d63df9de4/packages/eslint-config-react-app/index.js#L244

It's like a "Don't go faster then 130 on the highway" rule  but if you don't own a car you will never meet that rule. The only disadvantage is that your rule book becomes a bit bigger. But because this will be a dev dep it doesn't matter that much. Do you agree?

**Comment by vernondegoede** [comment]
Ok, agreed. Thanks all. I'm okay with extending from the existing config, especially since it's indeed just a dev dependency.
